/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountLayout: typeof import('./src/layouts/AccountLayout.vue')['default']
    Aside: typeof import('./src/layouts/default-layout/components/aside/Aside.vue')['default']
    AsideRight: typeof import('./src/layouts/default-layout/components/aside/Aside-right.vue')['default']
    AuthFooter: typeof import('./src/components/auth-footer/authFooter.vue')['default']
    AuthHeader: typeof import('./src/components/auth-header/authHeader.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    AuthMenu: typeof import('./src/components/auth-header/authMenu.vue')['default']
    ChangeListTable: typeof import('./src/components/change-list/changeListTable.vue')['default']
    CompleteProfile: typeof import('./src/components/auth/CompleteProfile.vue')['default']
    DataTable: typeof import('./src/components/data-table/dataTable.vue')['default']
    DefaultLayout: typeof import('./src/layouts/default-layout/DefaultLayout.vue')['default']
    Footer: typeof import('./src/layouts/default-layout/components/footer/Footer.vue')['default']
    FooterLegal: typeof import('./src/components/legal/FooterLegal.vue')['default']
    Header: typeof import('./src/layouts/default-layout/components/header/Header.vue')['default']
    HeaderLeagal: typeof import('./src/components/legal/HeaderLeagal.vue')['default']
    Legal: typeof import('./src/layouts/legal.vue')['default']
    LegalPrivacyPolicy: typeof import('./src/components/legal/LegalPrivacyPolicy.vue')['default']
    Menu: typeof import('./src/layouts/default-layout/components/aside/Menu.vue')['default']
    MenuLegal: typeof import('./src/components/legal/MenuLegal.vue')['default']
    RelationshipBadge: typeof import('./src/components/accounts/relationshipBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./src/components/auth/SignIn.vue')['default']
    SignUp: typeof import('./src/components/auth/SignUp.vue')['default']
    SystemLayout: typeof import('./src/layouts/SystemLayout.vue')['default']
    TermsOfService: typeof import('./src/components/legal/TermsOfService.vue')['default']
  }
}
