/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/accounts/': RouteRecordInfo<'/accounts/', '/accounts', Record<never, never>, Record<never, never>>,
    '/crafted/authentication/basic-flow/PasswordReset': RouteRecordInfo<'/crafted/authentication/basic-flow/PasswordReset', '/crafted/authentication/basic-flow/PasswordReset', Record<never, never>, Record<never, never>>,
    '/crafted/authentication/Error404': RouteRecordInfo<'/crafted/authentication/Error404', '/crafted/authentication/Error404', Record<never, never>, Record<never, never>>,
    '/crafted/authentication/Error500': RouteRecordInfo<'/crafted/authentication/Error500', '/crafted/authentication/Error500', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/LayoutBuilder': RouteRecordInfo<'/LayoutBuilder', '/LayoutBuilder', Record<never, never>, Record<never, never>>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/silque/Authentication': RouteRecordInfo<'/silque/Authentication', '/silque/Authentication', Record<never, never>, Record<never, never>>,
  }
}
